name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build frontend project
        run: npm run build
        working-directory: frontend

      - name: Upload frontend production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: frontend-production-files
          path: frontend/dist

  deploy:
    name: Deploy Frontend
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-production-files
          path: frontend/dist

      # Add your deployment steps here for the frontend
      # You can deploy the frontend to your desired hosting platform, such as GitHub Pages

      # Example: Deploy frontend to GitHub Pages
      - name: Deploy Frontend to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist
